title: Why We Vax?
logo: /assets/img/logo.png
description: Why We Vax? placeholder
show_downloads: false
theme: jekyll-theme-minimal

baseurl: "/WhyWeVax.github.io" # Repository name
url: "https://whywevax.github.io"

exclude:
  - LICENSE
  - README.md
  - run.sh

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
